version: '3.8'
services:

  web:
    container_name: web
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - resistance
    restart: always

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - $HOME/docker/volumes/postgres/:/var/lib/postgresql/data
    ports:
      - 5405:5432
    restart: always
    environment:
      - POSTGRES_USER=resistance
      - POSTGRES_PASSWORD=kjuyguyf24234cvbinm523b5yt6
      - POSTGRES_DB=resistance, resistance_test
      - POSTGRES_DBNAME=resistance, resistance_test
    networks:
      - resistance

networks:
  resistance:
